export const DCList = [
{
    name:`Batman`,
 description:'Kane conceived Batman in early 1939 to capitalize on the popularity of DC\'s Superman; although Kane frequently claimed sole creation credit, Finger substantially developed the concept from a generic superhero into something more bat-like. The character received his own spin-off publication, Batman, in 1940. Batman was originally introduced as a ruthless vigilante who frequently killed or maimed criminals, but evolved into a character with a stringent moral code and strong sense of justice. Unlike most superheroes, Batman does not possess any superpowers, instead relying on his intellect, fighting skills, and wealth. The 1960s Batman television series used a camp aesthetic, which continued to be associated with the character for years after the show ended. Various creators worked to return the character to his darker roots in the 1970s and 1980s, culminating with the 1986 miniseries The Dark Knight Returns by Frank Miller.'
},
{
    name:`Flash`,
    description:`The Flash (or simply Flash) is the name of several superheroes appearing in American comic books published by DC Comics. Created by writer Gardner Fox and artist Harry Lampert, the original Flash first appeared in Flash Comics #1 (cover date January 1940/release month November 1939).[1] Nicknamed the "Scarlet Speedster", all incarnations of the Flash possess "super speed", which includes the ability to run, move, and think extremely fast, use superhuman reflexes, and seemingly violate certain laws of physics.
                 Thus far, at least four different characters—each of whom somehow gained the power of "the speed force"—have assumed the mantle of the Flash in DC's history: college athlete Jay Garrick (1940–1951, 1961–2011, 2017–present), forensic scientist Barry Allen (1956–1985, 2008–present), Barry's nephew Wally West (1986–2011, 2016–present), and Barry's grandson Bart Allen (2006–2007). Each incarnation of the Flash has been a key member of at least one of DC's premier teams: the Justice Society of America, the Justice League, and the Teen Titans.`
},
{
  name:`Superman`,
  description:`Superman is a fictional character and a superhero who first appeared in American comic books published by DC Comics. The character was created by writer Jerry Siegel and artist Joe Shuster, and first appeared in the comic book Action Comics #1 (cover-dated June 1938 and published April 18, 1938).[1] Superman has been adapted to a number of other media which includes radio serials, novels, movies, television shows and theatre.
                Superman was born on the planet Krypton and was given the name Kal-El at birth. As a baby, his parents sent him to Earth in a small spaceship moments before Krypton was destroyed in a natural cataclysm. His ship landed in the American countryside, near the fictional town of Smallville. He was found and adopted by farmers Jonathan and Martha Kent, who named him Clark Kent. Clark developed various superhuman abilities, such as incredible strength and impervious skin. His adoptive parents advised him to use his abilities for the benefit of humanity, and he decided to fight crime as a vigilante. To protect his privacy, he changes into a colorful costume and uses the alias "Superman" when fighting crime. Clark Kent resides in the fictional American city of Metropolis, where he works as a journalist for the Daily Planet. Superman's supporting characters include his love interest and fellow journalist Lois Lane, Daily Planet photographer Jimmy Olsen and editor-in-chief Perry White. His archenemy is Lex Luthor, a mad scientist and ruthless businessman; his other enemies include Darkseid, Brainiac, General Zod, Doomsday, Metallo, and more.`
},
{
    name:`Dick Grayson`,
    description:`Richard John Grayson is a fictional superhero appearing in American comic books published by DC Comics, commonly in association with Batman. Created by writer Bill Finger and artist Bob Kane, he first appeared in Detective Comics #38 in April 1940 as the original and most popular incarnation of Robin, sidekick to the superhero Batman. In Tales of the Teen Titans #44 (July 1984) the character after becoming a young adult and in an effort to make himself a separate independent hero from Batman retires his role as Robin and assumes the superhero persona of Nightwing (created by Marv Wolfman and artist George Pérez).
                 The youngest in a family of acrobats known as the "Flying Graysons", Grayson witnesses a mafia boss named Tony Zucco kill his parents in order to extort money from the circus that employed them. After the tragic murder, Batman (Bruce Wayne) takes Grayson in as his legal ward (retconned as an adopted son in some cases) and trains him to become his crime-fighting partner Robin. He is written by many authors as the first son of Batman.[2] As well as being Batman's crime-fighting partner, Grayson establishes himself as the leader of the Teen Titans, a team of teenage superheroes. As a young man, he retires as Robin and takes on his own superhero identity to assert his independence, becoming Nightwing. As Nightwing, he continues to lead the Teen Titans and later the Outsiders. In the first volume of his eponymous series (1996–2009), he becomes the protector of Blüdhaven, Gotham's economically troubled neighboring city, the locale the character is most closely associated with. He has also been depicted as protecting the streets of New York, Chicago, and Gotham City over the years.`
},
{
    name:`Wonder Women`,
    description:`Wonder Woman is a superheroine appearing in American comic books published by DC Comics.[3] The character is a founding member of the Justice League. The character first appeared in All Star Comics #8 published October 21, 1941[1] with her first feature in Sensation Comics #1 in January 1942. The Wonder Woman title has been published by DC Comics almost continuously ever since.[4] In her homeland, the island nation of Themyscira, her official title is Princess Diana of Themyscira. When blending into the society outside of her homeland, she sometimes adopts her civilian identity Diana Prince.[5]
                 Wonder Woman was created by the American psychologist and writer William Moulton Marston (pen name: Charles Moulton),[2] and artist Harry G. Peter. Marston's wife, Elizabeth, and their life partner, Olive Byrne,[6] are credited as being his inspiration for the character's appearance.[2][7][8][9][10] Marston's comics featured his ideas on DISC theory,[11] and the character drew a great deal of inspiration from early feminists.`
},
{
    name:`Hal Jordan`,
    description:`Hal Jordan, also known as Green Lantern, is a fictional superhero appearing in American comic books published by DC Comics. The character was created in 1959 by writer John Broome and artist Gil Kane, and first appeared in Showcase #22 (October 1959). Hal Jordan is a reinvention of the previous Green Lantern who appeared in 1940s comic books as the character Alan Scott.
                 Hal Jordan is a former combat pilot who works for Ferris Aircraft as a test pilot, a member and occasionally leader of an intergalactic police force called the Green Lantern Corps, as well as a founding member of the Justice League, DC's flagship superhero team, alongside well-known heroes such as Batman, Superman, and Wonder Woman. He fights evil across the universe with a ring that grants him a variety of superpowers, but is usually portrayed as one of the protectors of Sector 2814, which is the sector where Earth resides. His powers derive from his power ring and Green Lantern battery, which in the hands of someone capable of overcoming great fear allows the user to channel their will power into creating all manner of fantastic constructs. Jordan uses this power to fly, even through the vacuum of space; to create shields, swords, and lasers; and to construct his Green Lantern costume, which protects his secret identity in his civilian life on Earth. Jordan and all other Green Lanterns are monitored and empowered by the mysterious Guardians of the Universe, who were developed from an idea editor Julius Schwartz and Broome had originally conceived years prior in a story featuring Captain Comet in Strange Adventures #22 (July 1952) entitled "Guardians of the Clockwork Universe".[1]`
},
{
    name:`Aquaman`,
    description:`Aquaman (Arthur Curry) is a fictional superhero appearing in American comic books published by DC Comics. Created by Paul Norris and Mort Weisinger, the character debuted in More Fun Comics #73 (Nov. 1941).[1] Initially a backup feature in DC's anthology titles, Aquaman later starred in several volumes of a solo comic book series. During the late 1950s and 1960s superhero-revival period known as the Silver Age, he was a founding member of the Justice League. In the 1990s Modern Age, writers interpreted Aquaman's character more seriously, with storylines depicting the weight of his role as king of Atlantis.[2]
                 The character's original 1960s animated appearances left a lasting impression, making Aquaman widely recognized in popular culture and one of the world's most recognized superheroes. Jokes about his wholesome, weak portrayal in Super Friends and perceived feeble powers and abilities have been staples of comedy programs and stand-up routines,[3][4][5] leading DC at several times to attempt to make the character edgier or more powerful in the comic books.[6] Modern comic book depictions have attempted to reconcile these various aspects of his public perception, with many versions often casting Aquaman as serious and brooding, saddled with an ill reputation, and struggling to find a true role and purpose beyond his public side as a deposed king and a fallen hero.[7]`
            },
{
    name:`Green Arrow`,
    description:`Green Arrow is a fictional character who appears in comic books published by DC Comics. Created by Mort Weisinger and designed by George Papp, he first appeared in More Fun Comics #73 in November 1941. His real name is Oliver Jonas Queen, a wealthy businessman and owner of Queen Industries who is also a well-known celebrity in Star City. He uses this position to hide the fact that he is the Arrow.[1] Sometimes shown dressed like the character Robin Hood, Green Arrow is an archer who uses his skills to fight crime in his home cities of Star City and Seattle, as well as alongside his fellow superheroes as a member of the Justice League. Though much less frequently used in modern stories, he also deploys a range of trick arrows (in contemporary times, they are referred as "specialty arrows"[2]) with various special functions, such as glue, explosive-tipped, grappling hook, flash grenade, tear gas and even kryptonite arrows for use in a range of special situations. At the time of his debut, Green Arrow functioned in many ways as an archery-themed analogue of the very popular Batman character, but writers at DC subsequently developed him into a voice of left-wing politics very much distinct in character from Batman.
                 Green Arrow enjoyed moderate success in his early years, becoming the cover feature of More Fun, as well as having occasional appearances in other comics. Throughout his first twenty-five years, however, the character never enjoyed greater popularity. In the late 1960s, writer Denny O'Neil, inspired by the character's dramatic visual redesign by Neal Adams, chose to have him lose his fortune, giving him the then-unique role of a streetwise crusader for the working class and the disadvantaged. In 1970, he was paired with a more law and order-oriented hero, Green Lantern, in a ground-breaking, socially conscious comic book series.[3] Since then, he has been popular among comic book fans and most writers have taken an urban, gritty approach to the character. The character was killed off in the 1990s and replaced by a new character, Oliver's son Connor Hawke. Connor, however, proved a less popular character, and the original Oliver Queen character was resurrected in the 2001 "Quiver" storyline, by writer Kevin Smith. In the 2000s, the character has been featured in bigger storylines focusing on Green Arrow and Black Canary, such as the DC event The Green Arrow/Black Canary Wedding and the high-profile Justice League: Cry for Justice storyline, prior to the character's relaunch alongside most of DC's properties in 2011.`
},
]
